"""Added credit to prof and client

Revision ID: 2163eb9bd9c5
Revises: 307960ba6212
Create Date: 2017-01-14 13:41:47.553000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2163eb9bd9c5'
down_revision = '307960ba6212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('credit', sa.Integer(), nullable=True))
    op.add_column('profs', sa.Column('credit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profs', 'credit')
    op.drop_column('clients', 'credit')
    # ### end Alembic commands ###
