"""added rate to profs model

Revision ID: 301dd5c388a0
Revises: 8ff1f39f9e9c
Create Date: 2017-01-17 12:52:42.793000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301dd5c388a0'
down_revision = '8ff1f39f9e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('time', sa.DateTime(), nullable=True))
    op.drop_column('bookings', 'hours')
    op.drop_column('bookings', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'time')
    # ### end Alembic commands ###
