"""Added subjects and levels

Revision ID: 307960ba6212
Revises: c4586ceed850
Create Date: 2017-01-13 20:23:45.665000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307960ba6212'
down_revision = 'c4586ceed850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    op.drop_table('levels')
    # ### end Alembic commands ###
