"""Added profs and clients models

Revision ID: 7e66e31147f6
Revises: 66352a7544c0
Create Date: 2017-01-11 14:22:03.540000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e66e31147f6'
down_revision = '66352a7544c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'users_username_key', 'users', type_='unique')
    op.drop_column(u'users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'users_username_key', 'users', ['username'])
    op.drop_table('profs')
    op.drop_table('clients')
    # ### end Alembic commands ###
