"""Added some datetime and timestamp attributes to Users and Bookings

Revision ID: 8ff1f39f9e9c
Revises: 2163eb9bd9c5
Create Date: 2017-01-14 14:14:49.100000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff1f39f9e9c'
down_revision = '2163eb9bd9c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'last_seen')
    op.drop_column('bookings', 'timestamp')
    # ### end Alembic commands ###
