"""added rate to profs model

Revision ID: a3e205aed75f
Revises: 301dd5c388a0
Create Date: 2017-01-17 12:54:44.569000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e205aed75f'
down_revision = '301dd5c388a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profs', sa.Column('rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profs', 'rate')
    # ### end Alembic commands ###
