"""Added accepted attribute to booking class

Revision ID: c4586ceed850
Revises: f50dc7b70013
Create Date: 2017-01-13 17:44:40.222000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4586ceed850'
down_revision = 'f50dc7b70013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'accepted')
    # ### end Alembic commands ###
